[package]
authors = ["taroosg <root@taroosg.dev>"]
edition = "2018"
name = "wasm"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]
[dependencies]
wasm-bindgen = "0.2.74"
[dev-dependencies]
wasm-bindgen-test = "0.3.0"
